name: "get & cache dependencies"
description: "Get dependencies and cache them"
inputs:
  caching:
    description: "determine dependencies will be cached or not"
    required: true
    default: "true"
outputs:
  cache-output:
    description: "output of custom job"
    value: ${{ }}
runs:
  using: composite
  steps:
    - name: Cache dependencies
      if: inputs.caching
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: Install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
        npm ci
        echo "::set-output name=cache::'${{inputs.caching}}'"
      shell: bash
